apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-app-config
  namespace: auth-app
data:
  TZ: Europe/Paris
  JWT_EXPIRATION_MS: "86400000"
  FRONTEND_URL: http://YOUR_SERVER_IP:30080
  MAIL_PORT: "587"
  MAIL_SMTP_AUTH: "true"
  MAIL_SMTP_STARTTLS: "true"
  MAIL_FROM: no-reply@example.com